export const Path = {
  ContactUs: "https://support.switcheo.network/en/",
  Feedback: "https://ideas.dem.exchange/",
  Socials: {
    Facebook: "https://www.facebook.com/SwitcheoExchange",
    LinkedIn: "https://www.linkedin.com/company/switcheo/",
    Twitter: "https://twitter.com/0xcarbon",
    DemexTwitter: "https://twitter.com/demexchange",
    Reddit: "https://www.reddit.com/r/Switcheo/",
    Telegram: "https://t.me/switcheo",
    Youtube: "https://www.youtube.com/channel/UCqZ9sxvw-0UoHzno4-d97oQ",
    Medium: "https://medium.com/switcheo",
    Discord: "https://discord.gg/SPh62Hf",
    Demex: "https://app.dem.exchange",
    Github: "https://github.com/switcheo",
    SwitcheoForum: "https://forum.carbon.network",
  },
  Footer: {
    Features: "/#features",
    Guides: "https://guide.carbon.network",
    Blog: "https://blog.switcheo.com",
    SWTH: "https://hub.carbon.network/",
    Stake: "https://app.dem.exchange/stake",
    Token: "https://scan.carbon.network/tokens?net=main",
    Markets: "https://scan.carbon.network/markets?net=main",
    Demex: "https://dem.exchange",
    CarbonScan: "https://scan.carbon.network",
    SwitcheoDevelopmentFund: "https://forum.carbon.network/topic/42/applying-for-project-grants-under-the-switcheo-development-fund",
    APIs: "https://docs.carbon.network",
    Github: "https://github.com/Switcheo",
    Forum: "https://forum.carbon.network",
    Governance: "https://scan.carbon.network/governance",
  },
  FindOutMore: "https://hub.carbon.network/",
};
