export const Path = {
  Header: {
    Build: "https://docs.carbon.network",
    SWTH: "https://hub.carbon.network/",
  },
  Feedback: "https://ideas.dem.exchange/",
  Socials: {
    LinkedIn: "https://www.linkedin.com/company/switcheo/",
    Twitter: "https://twitter.com/0xcarbon",
    Telegram: "https://t.me/carbon_ecosystem",
    Youtube: "https://www.youtube.com/channel/UCqZ9sxvw-0UoHzno4-d97oQ",
    Medium: "https://medium.com/switcheo",
    Discord: "https://discord.gg/SPh62Hf",
    Demex: "https://app.dem.exchange",
    Github: "https://github.com/Switcheo/carbon-bootstrap",
    SwitcheoForum: "https://commonwealth.im/carbon-protocol/discussions/Proposal%20Discussion",
  },
  Footer: {
    Features: "https://guide.carbon.network/features/cross-chain-interoperability",
    Guides: "https://guide.carbon.network",
    Blog: "https://blog.switcheo.com",
    Buy: "https://hub.carbon.network/buy",
    CarbonHub: "https://hub.carbon.network/",
    Stake: "https://app.dem.exchange/stake",
    Nitron: "https://app.dem.exchange/nitron",
    Token: "https://scan.carbon.network/tokens?net=main",
    Markets: "https://scan.carbon.network/markets?net=main",
    Demex: "https://dem.exchange",
    CarbonScan: "https://scan.carbon.network",
    Hydrogen: "https://hydrogen.carbon.network",
    SwitcheoDevelopmentFund: "https://commonwealth.im/carbon-protocol/discussion/4486-how-to-apply-for-a-grant-under-the-switcheo-development-fund",
    APIs: "https://docs.carbon.network/api-references",
    Github: "https://github.com/Switcheo/carbon-bootstrap/releases",
    SDK: "https://github.com/Switcheo/carbon-js-sdk",
    Forum: "https://commonwealth.im/carbon-protocol",
    Governance: "https://scan.carbon.network/governance",
    Setup: "https://docs.carbon.network/setting-up-a-node/mainnet-setup",
  },
  FindOutMore: "https://hub.carbon.network/",
};
