export const Path = {
  Header: {
    Build: "https://docs.carbon.network",
    SWTH: "https://hub.carbon.network/",
  },
  Feedback: "https://ideas.dem.exchange/",
  Socials: {
    LinkedIn: "https://www.linkedin.com/company/switcheo/",
    Twitter: "https://twitter.com/0xcarbon",
    Discussion: "https://t.me/carbon_ecosystem",
    Telegram: "https://t.me/carbon_ecosystem_ANN",
    Youtube: "https://www.youtube.com/channel/UCqZ9sxvw-0UoHzno4-d97oQ",
    Medium: "https://medium.com/switcheo",
    Discord: "https://discord.gg/SPh62Hf",
    Demex: "https://app.dem.exchange",
    Github: "https://github.com/Switcheo/carbon-bootstrap",
    SwitcheoForum: "https://commonwealth.im/carbon-protocol/discussions/Proposal%20Discussion",
  },
  Docs: {
    Discussion: "https://docs.carbon.network/module-architecture/carbon-evm",
    Guides: "https://docs.carbon.network/module-architecture/carbon-core",
  },
  Footer: {
    Features: "https://docs.carbon.network/carbon-core",
    Guides: "https://docs.carbon.network/introduction",
    Buy: "https://hub.carbon.network/buy",
    CarbonHub: "https://hub.carbon.network/",
    Stake: "https://hub.carbon.network/stake",
    Nitron: "https://app.dem.exchange/nitron",
    Token: "https://scan.carbon.network/tokens?net=main",
    Markets: "https://scan.carbon.network/markets?net=main",
    Demex: "https://dem.exchange",
    CarbonScan: "https://scan.carbon.network",
    Hydrogen: "https://hydrogen.carbon.network",
    SwitcheoDevelopmentFund: "https://guide.carbon.network/resources/carbon-development-fund",
    APIs: "https://docs.carbon.network/api-references",
    Github: "https://github.com/Switcheo/carbon-bootstrap/releases",
    SDK: "https://github.com/Switcheo/carbon-js-sdk",
    Forum: "https://commonwealth.im/carbon-protocol",
    Governance: "https://scan.carbon.network/governance",
    Setup: "https://docs.carbon.network/introduction/getting-started/carbon-node-setup",
    Research: "https://blog.switcheo.com/tag/research/",
    BrandAsset: "https://www.notion.so/Carbon-Media-Kit-819ec0d0ed7e45389da48ffd3dbfa6a2",
    Partnerships: "/partnerships",
  },
  FindOutMore: "https://hub.carbon.network/",
};
