version: 2.1
jobs:
  build:
    docker:
      # image with node, npm and yarn installed
      - image: cimg/node:20.5.0
        auth:
          username: $DOCKER_HUB_USERNAME
          password: $DOCKER_HUB_PASSWORD
    steps:

      # checkout workspace to repo code
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: yarn install
          command: yarn install --frozen-lockfile --network-concurrency 1

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      - run:
          name: build ReactJS project
          command: |
            yarn build

      - persist_to_workspace:
          root: .
          paths:
            - build

  deploy:
    docker:
      - image: cimg/gcp:2023.08
        auth:
          username: $DOCKER_HUB_USERNAME
          password: $DOCKER_HUB_PASSWORD
    steps:
      - attach_workspace:
          at: .

      - run:
          name: activate GCP service account
          command: |
            echo $GCP_SERVICE_KEY > ${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
            gcloud config set project $GCP_PROJECT_ID

      - run:
          name: deploy to gcp
          command: |
            gcloud storage cp -R build/* gs://carbon-website-${CIRCLE_BRANCH}/

workflows: 
  deploy-project:
    jobs:
      - build: 
          context: org-switcheo
          filters:
            branches:
              only:
                - master 
                - staging
      - deploy:
          context: org-switcheo
          requires:
            - build

